# Role: pod-reader - allows reading pods in rbac-test namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: rbac-test
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
---
# Role: secret-reader - for testing denied access
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
  namespace: rbac-test
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
