apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: canary-demo

resources:
  - deployment.yaml
  - canary.yaml

commonLabels:
  deployment-strategy: canary
  managed-by: fluxcd