apiVersion: batch/v1
kind: Job
metadata:
  name: data-processor
spec:
  template:
    metadata:
      labels:
        app: data-processor
        pattern: native-sidecar
    spec:
      restartPolicy: Never
      initContainers:
      # Sidecar that logs activity - doesn't block job completion
      - name: logger-sidecar
        image: busybox:1.36
        restartPolicy: Always  # Native sidecar
        command:
          - /bin/sh
          - -c
          - |
            echo "Logger sidecar started"
            while true; do
              echo "$(date): Logging activity..."
              sleep 2
            done

      containers:
      # Main job container - completes after 10 seconds
      - name: processor
        image: busybox:1.36
        command:
          - /bin/sh
          - -c
          - |
            echo "Processing data..."
            for i in 1 2 3 4 5; do
              echo "Processing batch #$i"
              sleep 2
            done
            echo "Job completed!"
