# Traditional Sidecar (PROBLEM: Job never completes)
apiVersion: batch/v1
kind: Job
metadata:
  name: batch-job-traditional
  labels:
    app: batch-job
    type: traditional
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: batch-job
        type: traditional
    spec:
      restartPolicy: OnFailure

      containers:
      # Main Job Container
      - name: batch-processor
        image: k8spatterns/batch-job:1.0
        imagePullPolicy: IfNotPresent
        env:
        - name: METRICS_FILE
          value: /data/metrics.json
        - name: TOTAL_ITEMS
          value: "50"
        volumeMounts:
        - name: shared-data
          mountPath: /data
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"

      # Traditional Sidecar (Problem: keeps running after job completes)
      - name: metrics-adapter
        image: k8spatterns/metrics-adapter:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9889
          name: metrics
        env:
        - name: METRICS_FILE
          value: /data/metrics.json
        - name: METRICS_PORT
          value: "9889"
        volumeMounts:
        - name: shared-data
          mountPath: /data
          readOnly: true
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"

      volumes:
      - name: shared-data
        emptyDir: {}
