apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-generator-green
  namespace: blue-green-demo
  labels:
    app: random-generator
    version: green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: random-generator
      version: green
  template:
    metadata:
      labels:
        app: random-generator
        version: green
    spec:
      containers:
      - name: random-generator
        image: k8spatterns/random-generator:2.0
        ports:
        - containerPort: 8080
        env:
        - name: PATTERN
          value: "Blue-Green (Green Version)"
        - name: VERSION
          value: "green"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5