apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blue-green-demo

resources:
  - deployment-blue.yaml
  - deployment-green.yaml
  - service.yaml

commonLabels:
  deployment-strategy: blue-green
  managed-by: fluxcd