apiVersion: v1
kind: Service
metadata:
  name: random-generator
  namespace: blue-green-demo
  labels:
    app: random-generator
spec:
  selector:
    app: random-generator
    version: blue  # 초기에는 blue를 가리킴
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
---
# Preview service for testing green before switching
apiVersion: v1
kind: Service
metadata:
  name: random-generator-preview
  namespace: blue-green-demo
  labels:
    app: random-generator
spec:
  selector:
    app: random-generator
    version: green  # Always points to green
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP