apiVersion: v1
kind: Pod
metadata:
  name: env-downward-demo
  namespace: default
  labels:
    app: random-generator
    version: "1.0"
    tier: backend
  annotations:
    description: "Self Awareness pattern - Environment Variables Demo"
    build: "test-001"
spec:
  containers:
  - name: random-generator
    image: busybox:1.36
    command: ["sh", "-c"]
    args:
    - |
      echo "=== Self Awareness Pattern - Environment Variables ==="
      echo ""
      echo "Pod Information:"
      echo "  Pod Name: $MY_POD_NAME"
      echo "  Namespace: $MY_POD_NAMESPACE"
      echo "  Pod IP: $MY_POD_IP"
      echo "  Node Name: $MY_NODE_NAME"
      echo "  Service Account: $MY_SERVICE_ACCOUNT"
      echo "  Pod UID: $MY_POD_UID"
      echo ""
      echo "Resource Information:"
      echo "  Memory Limit: ${MEMORY_LIMIT_MB} MB"
      echo "  CPU Limit: ${CPU_LIMIT_MILLICORES} milliCPU"
      echo "  Memory Request: ${MEMORY_REQUEST_MB} MB"
      echo "  CPU Request: ${CPU_REQUEST_MILLICORES} milliCPU"
      echo ""
      echo "Labels:"
      echo "  App Version: $APP_VERSION"
      echo "  Tier: $APP_TIER"
      echo ""
      echo "Host Information:"
      echo "  Host IP: $HOST_IP"
      echo ""
      echo "Keeping container running for 1 hour..."
      sleep 3600

    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"

    env:
    # Pod metadata from fieldRef
    - name: MY_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name

    - name: MY_POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace

    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP

    - name: MY_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName

    - name: MY_SERVICE_ACCOUNT
      valueFrom:
        fieldRef:
          fieldPath: spec.serviceAccountName

    - name: MY_POD_UID
      valueFrom:
        fieldRef:
          fieldPath: metadata.uid

    - name: HOST_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP

    # Labels
    - name: APP_VERSION
      valueFrom:
        fieldRef:
          fieldPath: metadata.labels['version']

    - name: APP_TIER
      valueFrom:
        fieldRef:
          fieldPath: metadata.labels['tier']

    # Resource limits and requests
    - name: MEMORY_LIMIT_MB
      valueFrom:
        resourceFieldRef:
          containerName: random-generator
          resource: limits.memory
          divisor: "1Mi"

    - name: CPU_LIMIT_MILLICORES
      valueFrom:
        resourceFieldRef:
          containerName: random-generator
          resource: limits.cpu
          divisor: "1m"

    - name: MEMORY_REQUEST_MB
      valueFrom:
        resourceFieldRef:
          containerName: random-generator
          resource: requests.memory
          divisor: "1Mi"

    - name: CPU_REQUEST_MILLICORES
      valueFrom:
        resourceFieldRef:
          containerName: random-generator
          resource: requests.cpu
          divisor: "1m"
