apiVersion: v1
kind: Pod
metadata:
  name: dynamic-update-demo
  labels:
    app: label-watcher
    stage: alpha
    version: "1.0"
  annotations:
    config-version: "v1"
    updated-at: "initial"
spec:
  containers:
  - name: watcher
    image: busybox:1.36
    command: ["sh", "-c"]
    args:
    - |
      echo "=== Self Awareness Pattern - Dynamic Label/Annotation Updates ==="
      echo ""
      echo "This Pod demonstrates that labels and annotations"
      echo "mounted as volumes are updated dynamically when changed."
      echo ""
      echo "Initial state:"
      echo "--- Labels ---"
      cat /etc/podinfo/labels
      echo ""
      echo "--- Annotations ---"
      cat /etc/podinfo/annotations
      echo ""
      echo "========================================="
      echo "Watching for changes (checking every 5 seconds)..."
      echo "Update labels using:"
      echo "  kubectl label pod dynamic-update-demo stage=beta --overwrite"
      echo "  kubectl label pod dynamic-update-demo feature=new-api"
      echo ""
      echo "Update annotations using:"
      echo "  kubectl annotate pod dynamic-update-demo config-version=v2 --overwrite"
      echo "========================================="
      echo ""

      LABELS_FILE="/etc/podinfo/labels"
      ANNOTATIONS_FILE="/etc/podinfo/annotations"
      LAST_LABELS_MD5=""
      LAST_ANNOTATIONS_MD5=""

      while true; do
        CURRENT_LABELS_MD5=$(md5sum $LABELS_FILE | cut -d' ' -f1)
        CURRENT_ANNOTATIONS_MD5=$(md5sum $ANNOTATIONS_FILE | cut -d' ' -f1)

        if [ "$CURRENT_LABELS_MD5" != "$LAST_LABELS_MD5" ]; then
          echo ""
          echo "[$(date '+%Y-%m-%d %H:%M:%S')] LABELS CHANGED!"
          echo "--- Updated Labels ---"
          cat $LABELS_FILE
          echo ""
          LAST_LABELS_MD5=$CURRENT_LABELS_MD5
        fi

        if [ "$CURRENT_ANNOTATIONS_MD5" != "$LAST_ANNOTATIONS_MD5" ]; then
          echo ""
          echo "[$(date '+%Y-%m-%d %H:%M:%S')] ANNOTATIONS CHANGED!"
          echo "--- Updated Annotations ---"
          cat $ANNOTATIONS_FILE
          echo ""
          LAST_ANNOTATIONS_MD5=$CURRENT_ANNOTATIONS_MD5
        fi

        sleep 5
      done

    volumeMounts:
    - name: podinfo
      mountPath: /etc/podinfo
      readOnly: true

  volumes:
  - name: podinfo
    downwardAPI:
      items:
      - path: "labels"
        fieldRef:
          fieldPath: metadata.labels

      - path: "annotations"
        fieldRef:
          fieldPath: metadata.annotations
