# Liveness Probe - HTTP Health Check Test
# This deployment tests HTTP-based liveness probe functionality
apiVersion: apps/v1
kind: Deployment
metadata:
  name: liveness-http-test
  labels:
    test: liveness-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liveness-http-test
  template:
    metadata:
      labels:
        app: liveness-http-test
    spec:
      containers:
      - name: random-generator
        image: k8spatterns/random-generator:1.0
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: DELAY_STARTUP
          value: "10"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: liveness-http-test
spec:
  selector:
    app: liveness-http-test
  ports:
  - port: 8080
    targetPort: 8080
    name: http