# Liveness Probe - TCP Socket Check Test
# This deployment tests TCP socket-based liveness probe functionality
apiVersion: apps/v1
kind: Deployment
metadata:
  name: liveness-tcp-test
  labels:
    test: liveness-tcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liveness-tcp-test
  template:
    metadata:
      labels:
        app: liveness-tcp-test
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
          name: http
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: liveness-tcp-test
spec:
  selector:
    app: liveness-tcp-test
  ports:
  - port: 80
    targetPort: 80
    name: http