# Readiness Probe - Exec Command Check Test
# This deployment tests readiness probe with gradual ready state
apiVersion: apps/v1
kind: Deployment
metadata:
  name: readiness-exec-test
  labels:
    test: readiness-exec
spec:
  replicas: 3
  selector:
    matchLabels:
      app: readiness-exec-test
  template:
    metadata:
      labels:
        app: readiness-exec-test
    spec:
      containers:
      - name: random-generator
        image: k8spatterns/random-generator:1.0
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: DELAY_STARTUP
          value: "20"
        readinessProbe:
          exec:
            command:
            - stat
            - /tmp/random-generator-ready
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: readiness-exec-test
spec:
  selector:
    app: readiness-exec-test
  ports:
  - port: 8080
    targetPort: 8080
    name: http