# Readiness Probe - HTTP Check with Toggle Test
# This deployment tests HTTP-based readiness probe with toggle functionality
apiVersion: apps/v1
kind: Deployment
metadata:
  name: readiness-http-test
  labels:
    test: readiness-http
spec:
  replicas: 2
  selector:
    matchLabels:
      app: readiness-http-test
  template:
    metadata:
      labels:
        app: readiness-http-test
    spec:
      containers:
      - name: random-generator
        image: k8spatterns/random-generator:1.0
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: DELAY_STARTUP
          value: "5"
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 3
          timeoutSeconds: 2
          successThreshold: 2
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: readiness-http-test
spec:
  selector:
    app: readiness-http-test
  ports:
  - port: 8080
    targetPort: 8080
    name: http