# Readiness Gate - Custom Readiness Condition Test
# This deployment demonstrates custom readiness gates for advanced readiness checks
apiVersion: apps/v1
kind: Deployment
metadata:
  name: readiness-gate-test
  labels:
    test: readiness-gate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: readiness-gate-test
  template:
    metadata:
      labels:
        app: readiness-gate-test
    spec:
      # Custom readiness gate
      readinessGates:
      - conditionType: "k8spatterns.io/load-balancer-ready"
      containers:
      - name: random-generator
        image: k8spatterns/random-generator:1.0
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: DELAY_STARTUP
          value: "15"
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: readiness-gate-test
spec:
  selector:
    app: readiness-gate-test
  ports:
  - port: 8080
    targetPort: 8080
    name: http